name: api
description: An empty Aqueduct application with OAuth 2.0.
version: 0.0.1
author: Kevin Genus <kevin.genus@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
